# Generated by Django 3.1.3 on 2021-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('receipt_date', models.DateField()),
                ('type', models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('R', 'Reptile'), ('E', 'Else')], max_length=2)),
                ('sterilized', models.BooleanField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
    ]
